name: Feature Request ✨
description: Suggest a feature for Equal Library 🧬
title: '[ Feature Request ] <title>'
labels: [ 'feature' ]
body:
  
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      value: "Ex. I'm always frustrated when [...]"
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Adding some code examples would be neat!
      render: markdown
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      render: markdown
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      render: markdown
    validations:
      required: false

